import { AppContainer } from "components/app/AppContainer";
import "./globals.css";
import type { Metadata } from "next";
import { AppProvider } from "components/app/AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppContainer>
      <AppProvider>{children}</AppProvider>
    </AppContainer>
  );
}
